import type { DetectedRoute } from './frameworks/index.js';
import { buildRouteContext, chunkRoutes } from './prompt.js';

export function buildOpenApiSystemPrompt(): string {
  return `You are apiscribe, an API documentation generator. Your job is to analyze backend route handler source code and produce a valid OpenAPI 3.0.3 JSON specification for every API endpoint found.

RULES:
1. Output ONLY valid JSON. No markdown, no code fences, no commentary before or after the JSON.
2. The JSON must conform to the OpenAPI 3.0.3 specification.
3. Document EVERY endpoint you find in the provided code. Do not skip any.
4. The endpoint URL paths provided alongside each file are pre-computed from the filesystem structure. Use them as the canonical URL for each endpoint. Do NOT guess different URLs.
5. If a single file exports multiple HTTP method handlers (e.g., GET and POST), document each as a separate operation under the same path.
6. Be precise about types. If you see TypeScript interfaces or Zod schemas, use them to build accurate schemas.
7. Note authentication patterns (Bearer token, cookies, API keys) in securitySchemes.
8. Do NOT fabricate parameters or response fields not present in the code.
9. Use "tags" to group endpoints logically by their path prefix (e.g., all /api/marketplace/* endpoints under "Marketplace").
10. Be CONCISE. Only include response schemas for the main success case. Skip detailed error response schemas — just list the status code and a short description.
11. Do NOT include example values unless they are critical to understanding the endpoint.
12. For the "info" section:
    - "title" should be a descriptive name derived from the project (e.g., "Billix API", "LAW 4 ME API"), NOT "API Documentation".
    - "description" should be a 2-3 sentence overview of what the API does, based on the endpoints you see. Mention the main capabilities (e.g., "Manages bill uploads, marketplace contributions, and housing market data").
13. Include a "servers" array with a placeholder entry: [{"url": "https://your-project.supabase.co", "description": "Production server"}] for Supabase projects, or [{"url": "http://localhost:3000", "description": "Development server"}] for others.
14. If you detect authentication patterns (Bearer tokens, API keys, Supabase auth), document them in "components.securitySchemes" AND add a brief note in "info.description" about how authentication works.`;
}

export function buildOpenApiUserPrompt(
  routes: DetectedRoute[],
  detectedFrameworks: string[],
): string {
  const context = buildRouteContext(routes, detectedFrameworks);

  const outputFormat = `\n## Output Format

Output a single valid JSON object conforming to OpenAPI 3.0.3. Use this exact structure:

{
  "openapi": "3.0.3",
  "info": {
    "title": "Your Project Name API",
    "version": "1.0.0",
    "description": "Brief 2-3 sentence overview of the API capabilities. Mention authentication if applicable. Generated by apiscribe."
  },
  "servers": [
    { "url": "https://your-project.supabase.co", "description": "Production server" }
  ],
  "tags": [
    { "name": "Group Name", "description": "Description of the group" }
  ],
  "paths": {
    "/api/example": {
      "get": {
        "tags": ["Group Name"],
        "summary": "Brief description",
        "operationId": "getExample",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": { "type": "string" },
            "description": "The resource ID"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          },
          "400": { "description": "Bad request" },
          "401": { "description": "Unauthorized" }
        },
        "security": [{ "bearerAuth": [] }]
      }
    }
  },
  "components": {
    "schemas": {},
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}

IMPORTANT:
- Use the exact endpoint paths provided in "Inferred endpoint path" above. Do not modify them.
- Convert path parameters like :id to {id} in the OpenAPI paths.
- Output ONLY the JSON object. No text before or after it.`;

  return context + outputFormat;
}

export function buildOpenApiPromptChunks(
  routes: DetectedRoute[],
  detectedFrameworks: string[],
  maxTokensPerChunk = 10000,
): string[] {
  const chunks = chunkRoutes(routes, maxTokensPerChunk);

  if (chunks.length === 1) {
    return [buildOpenApiUserPrompt(chunks[0], detectedFrameworks)];
  }

  return chunks.map((chunk) => buildOpenApiUserPrompt(chunk, detectedFrameworks));
}

export function extractAndValidateOpenApiJson(raw: string): Record<string, any> {
  let cleaned = raw.trim();

  // Strip markdown code fences if present
  const fenceMatch = cleaned.match(/```(?:json)?\s*\n([\s\S]*?)\n```/);
  if (fenceMatch) {
    cleaned = fenceMatch[1].trim();
  }

  // Try direct parse
  try {
    const parsed = JSON.parse(cleaned);
    return validateOpenApiStructure(parsed);
  } catch {
    // Continue to repair attempts
  }

  // Try extracting from first { to last }
  const firstBrace = cleaned.indexOf('{');
  const lastBrace = cleaned.lastIndexOf('}');
  if (firstBrace !== -1 && lastBrace > firstBrace) {
    const substring = cleaned.slice(firstBrace, lastBrace + 1);
    try {
      const parsed = JSON.parse(substring);
      return validateOpenApiStructure(parsed);
    } catch {
      // Continue to repair
    }

    // Remove trailing commas before } or ]
    const repaired = substring.replace(/,\s*([}\]])/g, '$1');
    try {
      const parsed = JSON.parse(repaired);
      return validateOpenApiStructure(parsed);
    } catch {
      // Give up
    }
  }

  throw new Error('Failed to parse OpenAPI JSON from LLM response. The output was not valid JSON.');
}

function validateOpenApiStructure(spec: Record<string, any>): Record<string, any> {
  if (!spec.openapi) {
    spec.openapi = '3.0.3';
  } else if (!spec.openapi.startsWith('3.0')) {
    spec.openapi = '3.0.3';
  }

  if (!spec.info) {
    spec.info = { title: 'API Documentation', version: '1.0.0' };
  }
  if (!spec.info.title) spec.info.title = 'API Documentation';
  if (!spec.info.version) spec.info.version = '1.0.0';

  if (!spec.paths) {
    spec.paths = {};
  }

  return spec;
}

export function mergeOpenApiSpecs(specs: Record<string, any>[]): Record<string, any> {
  if (specs.length === 1) return specs[0];

  const merged: Record<string, any> = {
    openapi: specs[0].openapi || '3.0.3',
    info: specs[0].info || { title: 'API Documentation', version: '1.0.0' },
    tags: [],
    paths: {},
    components: {
      schemas: {},
      securitySchemes: {},
    },
  };

  const seenTags = new Set<string>();

  for (const spec of specs) {
    // Merge tags
    if (Array.isArray(spec.tags)) {
      for (const tag of spec.tags) {
        if (tag.name && !seenTags.has(tag.name)) {
          seenTags.add(tag.name);
          merged.tags.push(tag);
        }
      }
    }

    // Merge paths
    if (spec.paths) {
      for (const [path, pathItem] of Object.entries(spec.paths)) {
        if (!merged.paths[path]) {
          merged.paths[path] = pathItem;
        } else {
          Object.assign(merged.paths[path], pathItem);
        }
      }
    }

    // Merge components
    if (spec.components) {
      if (spec.components.schemas) {
        Object.assign(merged.components.schemas, spec.components.schemas);
      }
      if (spec.components.securitySchemes) {
        Object.assign(merged.components.securitySchemes, spec.components.securitySchemes);
      }
    }
  }

  // Clean up empty sections
  if (merged.tags.length === 0) delete merged.tags;
  if (Object.keys(merged.components.schemas).length === 0) delete merged.components.schemas;
  if (Object.keys(merged.components.securitySchemes).length === 0)
    delete merged.components.securitySchemes;
  if (merged.components && Object.keys(merged.components).length === 0) delete merged.components;

  return merged;
}

export function generateScalarHtml(spec: Record<string, any>): string {
  const title = spec.info?.title || 'API Reference';
  const specJson = JSON.stringify(spec);

  return `<!DOCTYPE html>
<html>
<head>
  <title>${title}</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
<body>
  <script id="api-reference" type="application/json">${specJson}</script>
  <script>
    document.addEventListener('DOMContentLoaded', () => {
      const apiReference = document.getElementById('api-reference');
      if (apiReference) {
        apiReference.dataset.configuration = JSON.stringify({
          mcp: { disabled: true },
        });
      }
    });
  </script>
  <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
  <style>
    .scalar-app footer { display: none !important; }
    .scalar-app .deploy-button,
    .scalar-app [class*="deploy"] { display: none !important; }
  </style>
</body>
</html>`;
}
