import fs from 'node:fs/promises';
import path from 'node:path';
import type { ScanResult } from './scanner.js';
import { generateScalarHtml, type OpenApiSpec } from './openapi.js';

export interface OutputMeta {
  inputTokens: number;
  outputTokens: number;
  model: string;
}

export interface OutputOptions {
  outputPath: string;
  json: boolean;
}

function buildMetadataHeader(scanResult: ScanResult, meta: OutputMeta): string {
  return [
    '<!-- Generated by apiscribe (https://github.com/Overtaked00/apiscribe) -->',
    `<!-- Frameworks: ${scanResult.detectedFrameworks.join(', ')} -->`,
    `<!-- Files scanned: ${scanResult.routes.length} -->`,
    `<!-- Model: ${meta.model} -->`,
    `<!-- Tokens: ${meta.inputTokens.toLocaleString()} in / ${meta.outputTokens.toLocaleString()} out -->`,
    `<!-- Generated: ${new Date().toISOString()} -->`,
  ].join('\n');
}

export function mergeDocumentationChunks(chunks: string[]): string {
  if (chunks.length === 1) return chunks[0];

  const allSections: string[] = [];

  for (const chunk of chunks) {
    const sections = chunk.split(/^## /m).slice(1);
    const endpointSections = sections.filter(
      (s) => !s.toLowerCase().startsWith('table of contents'),
    );
    allSections.push(...endpointSections.map((s) => '## ' + s));
  }

  const header = `# API Documentation\n\n> Generated by apiscribe on ${new Date().toISOString().split('T')[0]}\n`;
  return header + '\n' + allSections.join('\n');
}

export async function writeOutput(
  content: string,
  scanResult: ScanResult,
  meta: OutputMeta,
  options: OutputOptions,
): Promise<void> {
  if (options.json) {
    const jsonPath = options.outputPath.replace(/\.md$/, '.json');
    const jsonContent = extractJsonFromMarkdown(content);
    await fs.writeFile(jsonPath, jsonContent, 'utf-8');
  } else {
    const header = buildMetadataHeader(scanResult, meta);
    const fullContent = header + '\n\n' + content;
    await fs.writeFile(options.outputPath, fullContent, 'utf-8');
  }
}

function extractJsonFromMarkdown(content: string): string {
  const jsonBlockMatch = content.match(/```(?:json)?\s*\n([\s\S]*?)\n```/);
  if (jsonBlockMatch) {
    try {
      JSON.parse(jsonBlockMatch[1]);
      return jsonBlockMatch[1];
    } catch {
      // Not valid JSON, fall through
    }
  }

  try {
    JSON.parse(content);
    return content;
  } catch {
    return JSON.stringify({ raw: content }, null, 2);
  }
}

export async function writeOpenApiOutput(
  spec: OpenApiSpec,
  options: { outputPath: string; writeHtml: boolean },
): Promise<{ specPath: string; htmlPath?: string }> {
  const dir = path.dirname(options.outputPath);
  const specPath = path.join(dir, 'openapi.json');
  await fs.writeFile(specPath, JSON.stringify(spec, null, 2), 'utf-8');

  const result: { specPath: string; htmlPath?: string } = { specPath };

  if (options.writeHtml) {
    const htmlPath = path.join(dir, 'index.html');
    const html = generateScalarHtml(spec);
    await fs.writeFile(htmlPath, html, 'utf-8');
    result.htmlPath = htmlPath;
  }

  return result;
}
