import type { DetectedRoute } from './frameworks/index.js';
import { getDetectors } from './frameworks/index.js';

function estimateTokens(text: string): number {
  return Math.ceil(text.length / 4);
}

export function buildRouteContext(routes: DetectedRoute[], detectedFrameworks: string[]): string {
  const parts: string[] = [];
  const detectors = getDetectors();

  parts.push('## Framework Context\n');
  for (const fw of detectedFrameworks) {
    const detector = detectors.find((d) => d.name === fw);
    if (detector) {
      parts.push(`### ${detector.name}\n${detector.promptHint}\n`);
    }
  }

  parts.push('\n## Route Files\n');
  parts.push(`Total: ${routes.length} files\n`);

  for (const route of routes) {
    parts.push(`\n### File: ${route.relativePath}`);
    parts.push(`Framework: ${route.framework}`);
    parts.push(`Inferred endpoint path: ${route.inferredPath}`);
    parts.push(`HTTP methods detected: ${route.httpMethods.join(', ')}`);
    parts.push('```typescript');
    parts.push(route.content);
    parts.push('```\n');
  }

  return parts.join('\n');
}

export function chunkRoutes(routes: DetectedRoute[], maxTokensPerChunk = 60000): DetectedRoute[][] {
  const totalCodeTokens = routes.reduce((sum, r) => sum + estimateTokens(r.content), 0);

  if (totalCodeTokens <= maxTokensPerChunk) {
    return [routes];
  }

  const sorted = [...routes].sort((a, b) => {
    if (a.framework !== b.framework) return a.framework.localeCompare(b.framework);
    return a.inferredPath.localeCompare(b.inferredPath);
  });

  const chunks: DetectedRoute[][] = [];
  let currentChunk: DetectedRoute[] = [];
  let currentTokens = 0;

  for (const route of sorted) {
    const routeTokens = estimateTokens(route.content) + 200;
    if (currentTokens + routeTokens > maxTokensPerChunk && currentChunk.length > 0) {
      chunks.push(currentChunk);
      currentChunk = [];
      currentTokens = 0;
    }
    currentChunk.push(route);
    currentTokens += routeTokens;
  }
  if (currentChunk.length > 0) chunks.push(currentChunk);

  return chunks;
}

export function buildSystemPrompt(): string {
  return `You are apiscribe, an API documentation generator. Your job is to analyze backend route handler source code and produce comprehensive, accurate markdown documentation for every API endpoint found.

RULES:
1. Document EVERY endpoint you find in the provided code. Do not skip any.
2. The endpoint URL paths provided alongside each file are pre-computed from the filesystem structure. Use them as the canonical URL for each endpoint. Do NOT guess different URLs.
3. For each endpoint, document: HTTP method, URL path, description, request parameters (path params, query params, request body with types), response format (success and error), authentication requirements, and any notable behavior.
4. If a single file exports multiple HTTP method handlers (e.g., GET and POST), document each as a separate endpoint.
5. Be precise about types. If you see TypeScript interfaces or Zod schemas, use them.
6. Note authentication patterns (Bearer token, cookies, API keys).
7. Note rate limiting if present.
8. Do NOT fabricate parameters or response fields not present in the code.`;
}

export function buildUserPrompt(routes: DetectedRoute[], detectedFrameworks: string[]): string {
  const context = buildRouteContext(routes, detectedFrameworks);

  const outputFormat = `\n## Output Format

Generate a complete Markdown document with the following structure:

# API Documentation

> Generated by apiscribe
> Frameworks detected: [list]
> Total endpoints: [count]

## Table of Contents
[Auto-generated from endpoint groups]

## [Group Name]

Group endpoints logically by their path prefix (e.g., all /api/marketplace/* endpoints under "Marketplace").
For Supabase Edge Functions, group by function purpose.

### [HTTP_METHOD] [endpoint_path]

**Description:** [1-2 sentence description of what this endpoint does]

**Authentication:** [Required/Optional/None — specify method if required]

**Request:**
- **Path Parameters:** [table with name, type, description — or "None"]
- **Query Parameters:** [table with name, type, required, description — or "None"]
- **Request Body:**
\`\`\`json
{
  "field": "type — description"
}
\`\`\`

**Response:**
- **Success (200):**
\`\`\`json
{
  "field": "type — description"
}
\`\`\`
- **Error Responses:** [list status codes and their meaning]

**Notes:** [Rate limiting, special behavior, webhook triggers, etc. — or omit if none]

---

IMPORTANT: Use the exact endpoint paths provided in "Inferred endpoint path" above. Do not modify them.`;

  return context + outputFormat;
}

export function buildPromptChunks(
  routes: DetectedRoute[],
  detectedFrameworks: string[],
  maxTokensPerChunk = 60000,
): string[] {
  const chunks = chunkRoutes(routes, maxTokensPerChunk);
  return chunks.map((chunk) => buildUserPrompt(chunk, detectedFrameworks));
}
